-- Add 35 general Bible knowledge questions to weekly quiz ID 1
-- This will fix the empty page issue

INSERT INTO weekly_quiz_questions (weekly_quiz_id, question, option_a, option_b, option_c, option_d, correct_index, order_index) VALUES
(1, 'Which biblical figure lived the longest according to Scripture?', 'Methuselah (969 years)', 'Jared (962 years)', 'Noah (950 years)', 'Adam (930 years)', 0, 1),
(1, 'What is the exact number of verses in Psalm 119?', '176', '150', '200', '180', 0, 2),
(1, 'Which book contains the most references to "love" in the Bible?', '1 John', 'Psalms', 'Song of Solomon', '1 Corinthians', 0, 3),
(1, 'What is the Hebrew meaning of "Immanuel"?', 'God with us', 'God is love', 'God is great', 'God is good', 0, 4),
(1, 'Which biblical character is mentioned by name in both Old and New Testaments?', 'Melchizedek', 'Abraham', 'Moses', 'David', 0, 5),
(1, 'What is the longest single word in the original Hebrew Bible?', 'Mahershalalhashbaz', 'Nebuchadnezzar', 'Melchizedek', 'Jehoshaphat', 0, 6),
(1, 'Which Gospel was written by a physician?', 'Luke', 'Mark', 'John', 'Matthew', 0, 7),
(1, 'What is the only book in the Bible that doesn''t mention God?', 'Esther', 'Song of Solomon', 'Ecclesiastes', 'Ruth', 0, 8),
(1, 'Which biblical character had 12 sons who became the 12 tribes of Israel?', 'Jacob', 'Abraham', 'Isaac', 'Joseph', 0, 9),
(1, 'What is the exact number of times "love" appears in 1 Corinthians 13?', '0 times', '1 time', '3 times', '5 times', 0, 10),
(1, 'Which prophet was taken to heaven without dying?', 'Elijah', 'Enoch', 'Moses', 'Elisha', 0, 11),
(1, 'What is the meaning of "Jehovah Jireh"?', 'The Lord will provide', 'The Lord is my shepherd', 'The Lord is my rock', 'The Lord is my light', 0, 12),
(1, 'Which book of the Bible contains the most chapters?', 'Psalms (150 chapters)', 'Genesis (50 chapters)', 'Isaiah (66 chapters)', 'Jeremiah (52 chapters)', 0, 13),
(1, 'What is the shortest verse in the original Greek New Testament?', 'Jesus wept (John 11:35)', 'Rejoice always (1 Thess 5:16)', 'Pray continually (1 Thess 5:17)', 'Love one another (John 13:34)', 0, 14),
(1, 'Which biblical character was known as "the weeping prophet"?', 'Jeremiah', 'Isaiah', 'Ezekiel', 'Daniel', 0, 15),
(1, 'What is the meaning of "El Shaddai"?', 'God Almighty', 'God Most High', 'God of Hosts', 'God of Love', 0, 16),
(1, 'Which book contains the famous "love chapter" of the Bible?', '1 Corinthians 13', '1 John 4', 'Song of Solomon', 'Romans 8', 0, 17),
(1, 'What is the exact number of words in the shortest verse in English?', '2 words', '3 words', '4 words', '5 words', 0, 18),
(1, 'Which biblical character was known as "the man after God''s own heart"?', 'David', 'Moses', 'Abraham', 'Solomon', 0, 19),
(1, 'What is the meaning of "Jehovah Rapha"?', 'The Lord who heals', 'The Lord who provides', 'The Lord who saves', 'The Lord who protects', 0, 20),
(1, 'Which book of the Bible is considered the "Gospel of the Kingdom"?', 'Matthew', 'Mark', 'Luke', 'John', 0, 21),
(1, 'What is the exact number of times "faith" appears in Hebrews 11?', '24 times', '20 times', '28 times', '32 times', 0, 22),
(1, 'Which biblical character was known as "the friend of God"?', 'Abraham', 'Moses', 'David', 'Noah', 0, 23),
(1, 'What is the meaning of "Jehovah Nissi"?', 'The Lord is my banner', 'The Lord is my shepherd', 'The Lord is my rock', 'The Lord is my light', 0, 24),
(1, 'Which book contains the most detailed description of the temple?', 'Ezekiel', '1 Kings', '2 Chronicles', 'Ezra', 0, 25),
(1, 'What is the exact number of times "grace" appears in the New Testament?', 'Over 150 times', 'Over 100 times', 'Over 200 times', 'Over 250 times', 0, 26),
(1, 'Which biblical character was known as "the father of many nations"?', 'Abraham', 'Isaac', 'Jacob', 'Noah', 0, 27),
(1, 'What is the meaning of "Jehovah Shalom"?', 'The Lord is peace', 'The Lord is my shepherd', 'The Lord is my rock', 'The Lord is my light', 0, 28),
(1, 'Which book of the Bible contains the most detailed genealogy?', '1 Chronicles', 'Genesis', 'Matthew', 'Luke', 0, 29),
(1, 'What is the exact number of times "hope" appears in the New Testament?', 'Over 50 times', 'Over 30 times', 'Over 70 times', 'Over 90 times', 0, 30),
(1, 'Which biblical character was known as "the weeping prophet"?', 'Jeremiah', 'Isaiah', 'Ezekiel', 'Daniel', 0, 31),
(1, 'What is the meaning of "Jehovah Tsidkenu"?', 'The Lord our righteousness', 'The Lord our shepherd', 'The Lord our rock', 'The Lord our light', 0, 32),
(1, 'Which book contains the most detailed description of the creation?', 'Genesis 1', 'Psalm 104', 'Job 38', 'Isaiah 40', 0, 33),
(1, 'What is the exact number of times "peace" appears in the New Testament?', 'Over 90 times', 'Over 70 times', 'Over 110 times', 'Over 130 times', 0, 34),
(1, 'Which biblical character was known as "the man of sorrows"?', 'Jesus Christ', 'Jeremiah', 'Job', 'David', 0, 35);
