-- Connections Table
create table if not exists public.connections (
  id bigint generated by default as identity primary key,
  requester_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(requester_id, receiver_id)
);

-- Realtime
alter publication supabase_realtime add table connections;

-- Policies
alter table public.connections enable row level security;

-- Users can see their own connections (sent or received)
create policy "Users can view their own connections" 
on public.connections for select 
using (auth.uid() = requester_id or auth.uid() = receiver_id);

-- Users can send requests
create policy "Users can insert connection requests" 
on public.connections for insert 
with check (auth.uid() = requester_id);

-- Users can update connections (accept/reject) if they are involved
create policy "Users can update their own connections" 
on public.connections for update 
using (auth.uid() = requester_id or auth.uid() = receiver_id);

-- Users can delete connections (unfriend/cancel) if they are involved
create policy "Users can delete their own connections" 
on public.connections for delete 
using (auth.uid() = requester_id or auth.uid() = receiver_id);

-- Helper View to see Connection Details with Profile Data
create or replace view public.connections_detailed as
select 
  c.id,
  c.status,
  c.created_at,
  c.requester_id,
  c.receiver_id,
  p_req.full_name as requester_name,
  -- p_req.avatar_url as requester_avatar, -- Removed as column doesn't exist
  p_rec.full_name as receiver_name
  -- p_rec.avatar_url as receiver_avatar -- Removed as column doesn't exist
from connections c
join profiles p_req on c.requester_id = p_req.id
join profiles p_rec on c.receiver_id = p_rec.id;
