-- Create flagged_posts table
create table if not exists public.flagged_posts (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts on delete cascade not null,
  user_id uuid references auth.users not null, -- The user who flagged the post
  reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id) -- Prevent multiple flags by same user on same post
);

-- Enable RLS
alter table public.flagged_posts enable row level security;

-- Policies
create policy "Users can insert their own flags" on public.flagged_posts 
  for insert with check (auth.uid() = user_id);

create policy "Admins can view flagged posts" on public.flagged_posts 
  for select using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );
