module.exports = {
  // Include all your important routes for pre-rendering
  include: [
    '/',
    '/articles',
    '/public-leaderboard',
    '/host-live-bible-quizzes-with-confidence',
    '/bible-questions-and-answers-hub',
    '/bible-questions-and-answers-hub/genesis',
    // Genesis chapters
    '/bible-questions-and-answers-hub/genesis/chapter-1',
    '/bible-questions-and-answers-hub/genesis/chapter-2',
    '/bible-questions-and-answers-hub/genesis/chapter-3',
    '/bible-questions-and-answers-hub/genesis/chapter-4',
    '/bible-questions-and-answers-hub/genesis/chapter-5',
    '/bible-questions-and-answers-hub/genesis/chapter-6',
    '/bible-questions-and-answers-hub/genesis/chapter-7',
    '/bible-questions-and-answers-hub/genesis/chapter-8',
    // Genesis full chapters
    '/bible-questions-and-answers-hub/genesis/chapter-1-full',
    '/bible-questions-and-answers-hub/genesis/chapter-2-full',
    '/bible-questions-and-answers-hub/genesis/chapter-3-full',
    // Public quiz pages - Pentateuch
    '/public-quiz/genesis',
    '/public-quiz/exodus',
    '/public-quiz/leviticus',
    '/public-quiz/numbers',
    '/public-quiz/deuteronomy',
    // Historical books
    '/public-quiz/joshua',
    '/public-quiz/judges',
    '/public-quiz/ruth',
    '/public-quiz/1-samuel',
    '/public-quiz/2-samuel',
    '/public-quiz/1-kings',
    '/public-quiz/2-kings',
    '/public-quiz/1-chronicles',
    '/public-quiz/2-chronicles',
    '/public-quiz/ezra',
    '/public-quiz/nehemiah',
    '/public-quiz/esther',
    // Wisdom literature
    '/public-quiz/job',
    '/public-quiz/psalms',
    '/public-quiz/proverbs',
    '/public-quiz/ecclesiastes',
    '/public-quiz/song-of-solomon',
    // Major prophets
    '/public-quiz/isaiah',
    '/public-quiz/jeremiah',
    '/public-quiz/lamentations',
    '/public-quiz/ezekiel',
    '/public-quiz/daniel',
    // Minor prophets
    '/public-quiz/hosea',
    '/public-quiz/joel',
    '/public-quiz/amos',
    '/public-quiz/obadiah',
    '/public-quiz/jonah',
    '/public-quiz/micah',
    '/public-quiz/nahum',
    '/public-quiz/habakkuk',
    '/public-quiz/zephaniah',
    '/public-quiz/haggai',
    '/public-quiz/zechariah',
    '/public-quiz/malachi',
    // Gospels
    '/public-quiz/matthew',
    '/public-quiz/mark',
    '/public-quiz/luke',
    '/public-quiz/john',
    // Acts and epistles
    '/public-quiz/acts',
    '/public-quiz/romans',
    '/public-quiz/1-corinthians',
    '/public-quiz/2-corinthians',
    '/public-quiz/galatians',
    '/public-quiz/ephesians',
    '/public-quiz/philippians',
    '/public-quiz/colossians',
    '/public-quiz/1-thessalonians',
    '/public-quiz/2-thessalonians',
    '/public-quiz/1-timothy',
    '/public-quiz/2-timothy',
    '/public-quiz/titus',
    '/public-quiz/philemon',
    '/public-quiz/hebrews',
    '/public-quiz/james',
    '/public-quiz/1-peter',
    '/public-quiz/2-peter',
    '/public-quiz/1-john',
    '/public-quiz/2-john',
    '/public-quiz/3-john',
    '/public-quiz/jude',
    '/public-quiz/revelation',
    // Article pages
    '/articles/complete-quiz-guide',
    '/articles/quiz-strategies',
    '/articles/leaderboard-tips',
    '/articles/david-king-israel',
    '/articles/moses-exodus-story',
    '/articles/esther-courage-story',
    '/articles/understanding-grace',
    '/articles/prayer-life-guide',
    '/articles/quiz-time-management',
    '/articles/bible-study-methods',
    '/articles/quiz-navigation-guide',
    '/articles/quiz-scoring-explained',
    '/articles/quiz-difficulty-levels',
    '/articles/quiz-feedback-system',
    '/articles/quiz-progress-tracking',
    '/articles/memory-techniques-quiz',
    '/articles/quiz-anxiety-management',
    '/articles/question-pattern-recognition',
    '/articles/quiz-concentration-techniques',
    '/articles/quiz-recovery-strategies',
    '/articles/competition-preparation',
    '/articles/team-quiz-strategies',
    '/articles/competition-psychology',
    '/articles/competition-etiquette',
    '/articles/post-competition-analysis',
    '/articles/moses-leadership-lessons',
    '/articles/esther-strategic-wisdom',
    '/articles/abraham-faith-journey',
    '/articles/joseph-forgiveness-story',
    '/articles/ruth-loyalty-devotion',
    '/articles/forgiveness-healing-power',
    '/articles/hope-biblical-perspective',
    '/articles/love-gods-greatest-commandment',
    '/articles/faith-works-james',
    '/articles/peace-gods-promise',
    '/articles/scripture-memorization-techniques',
    '/articles/inductive-bible-study',
    '/articles/bible-study-journaling',
    '/articles/group-bible-study-leading',
    '/articles/bible-study-technology'
  ],
  // Skip certain routes that don't need pre-rendering
  skipThirdPartyRequests: true,
  // Wait for content to load
  waitFor: 2000,
  // Remove scripts after pre-rendering
  removeBlobs: true,
  // Fix relative URLs
  fixWebpackChunksIssue: true,
  // Preload all routes
  preload: true,
  // Cache AJAX requests
  cacheAjaxRequests: true,
  // Skip certain file types
  skipThirdPartyRequests: true,
  // User agent for rendering
  userAgent: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
  // Custom headers
  headers: {
    'Accept-Language': 'en-US,en;q=0.9'
  }
};
