-- 1. Create Tables
-- Posts Table
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text,
  image_url text,
  type text default 'post', -- 'post' or 'achievement'
  achievement_data jsonb, -- Stores title, score, icon, color for achievements
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Likes Table
create table if not exists public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  post_id bigint references public.posts on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

-- Comments Table
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  post_id bigint references public.posts on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Realtime
-- Check if publication exists, if not create it (rarely needed if default exists, but good practice)
-- Usually 'supabase_realtime' exists. We just add tables.
alter publication supabase_realtime add table posts;
alter publication supabase_realtime add table likes;
alter publication supabase_realtime add table comments;

-- 3. Policies (RLS)
alter table public.posts enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;

create policy "Public posts are viewable by everyone" on public.posts for select using (true);
create policy "Users can insert their own posts" on public.posts for insert with check (auth.uid() = user_id);

create policy "Public likes are viewable by everyone" on public.likes for select using (true);
create policy "Users can insert their own likes" on public.likes for insert with check (auth.uid() = user_id);
create policy "Users can delete their own likes" on public.likes for delete using (auth.uid() = user_id);

create policy "Public comments are viewable by everyone" on public.comments for select using (true);
create policy "Users can insert their own comments" on public.comments for insert with check (auth.uid() = user_id);

-- 4. Views to helper fetching (Optional, but useful)
create or replace view public.posts_with_counts as
select 
  p.*,
  count(distinct l.id) as likes_count,
  count(distinct c.id) as comments_count,
  pr.full_name as user_name,
  NULL as user_avatar
from posts p
left join likes l on p.id = l.post_id
left join comments c on p.id = c.post_id
left join profiles pr on p.user_id = pr.id
group by p.id, pr.full_name;
