import { useParams } from "react-router-dom";
import PublicQuiz from "../PublicQuiz";
import { bookNames } from "@/data/bible-data";

export default function PublicQuizChapter() {
    const { book, chapter } = useParams();

    // Format book name (e.g., "1-samuel" -> "1 Samuel")
    const formattedBook = book ? bookNames[book.toLowerCase()] || book.charAt(0).toUpperCase() + book.slice(1) : "";
    const chapterNum = chapter ? chapter.replace('chapter-', '') : "1";

    // In a real app, we would fetch questions specific to this chapter here.
    // For now, we will use a generic set of questions or a placeholder to ensure the page renders
    // and serves its SEO purpose.
    // Ideally, we would have a huge database of questions mapped to chapters.

    const questions = [
        {
            id: 1,
            question: `What is a key theme in ${formattedBook} Chapter ${chapterNum}?`,
            options: ["Faith", "Obedience", "Love", "Depends on the context"],
            answer: 3,
            explanation: `Read ${formattedBook} Chapter ${chapterNum} to discover the specific themes and lessons.`
        },
        {
            id: 2,
            question: `Who is a main character in ${formattedBook} Chapter ${chapterNum}?`,
            options: ["Moses", "David", "Jesus", "Context specific"],
            answer: 3,
            explanation: `The characters vary by chapter. Study ${formattedBook} Chapter ${chapterNum} to find out!`
        },
        // We can add more generic questions or leave it light for now until real content is populated.
        // The key value here is the specific H1 and Title tags generated by PublicQuiz.
    ];

    return (
        <PublicQuiz
            title={`${formattedBook} Chapter ${chapterNum} Quiz`}
            questions={questions}
            bookName={formattedBook}
            chapter={chapterNum}
        />
    );
}
