
INSERT INTO weekly_quiz_questions (weekly_quiz_id, question, option_a, option_b, option_c, option_d, correct_index, order_index) VALUES
(11, 'Who is the recipient of Luke''s account?', 'Theophilus', 'Herod', 'Caesar', 'Pilate', 0, 1),
(11, 'Zechariah belonged to which priestly division?', 'Abijah', 'Aaron', 'Levi', 'Zadok', 0, 2),
(11, 'Elizabeth was a descendant of whom?', 'Aaron', 'David', 'Moses', 'Abraham', 0, 3),
(11, 'What was Zechariah doing when the angel appeared?', 'Burning incense', 'Reading the scroll', 'Cleaning the altar', 'Lighting the lamps', 0, 4),
(11, 'Where exactly did the angel stand?', 'Right side of the altar of incense', 'Left side of the altar', 'In the Holy of Holies', 'At the entrance', 0, 5),
(11, 'What is John forbidden to drink?', 'Wine or fermented drink', 'Water from the Jordan', 'Milk', 'Vinegar', 0, 6),
(11, 'John will go in the spirit and power of which prophet?', 'Elijah', 'Elisha', 'Isaiah', 'Jeremiah', 0, 7),
(11, 'What reason did the angel give for Zechariah''s silence?', 'He did not believe the words', 'He asked for a sign', 'He was too old', 'He was afraid', 0, 8),
(11, 'How long did Elizabeth stay in seclusion?', 'Five months', 'Three months', 'Six months', 'Nine months', 0, 9),
(11, 'In which month of Elizabeth''s pregnancy did the angel visit Mary?', 'Sixth', 'Fifth', 'Fourth', 'Seventh', 0, 10),
(11, 'Joseph was a descendant of whom?', 'David', 'Aaron', 'Saul', 'Solomon', 0, 11),
(11, 'What title will be given to the son of Mary?', 'Son of the Most High', 'Son of Man', 'King of Kings', 'Prince of Peace', 0, 12),
(11, 'How long will Jesus reign over Jacob''s descendants?', 'Forever', '1000 years', '40 years', 'Until the end of the age', 0, 13),
(11, 'What did the angel say would overshadow Mary?', 'The power of the Most High', 'A cloud of glory', 'The wings of angels', 'The spirit of prophecy', 0, 14),
(11, 'What relationship is Elizabeth to Mary?', 'Relative', 'Sister', 'Aunt', 'Mother', 0, 15),
(11, 'Where did Mary go "with haste"?', 'Hill country of Judea', 'Jerusalem', 'Galilee', 'Samaria', 0, 16),
(11, 'What happened to Elizabeth when Mary greeted her?', 'Filled with the Holy Spirit', 'She fainted', 'She began to weep', 'She fell silent', 0, 17),
(11, 'In Mary''s song, what does she say God has done to the rich?', 'Sent them away empty', 'Filled them with good things', 'Cast them down', 'Humbled them', 0, 18),
(11, 'How long did Mary stay with Elizabeth?', 'About three months', 'Six months', 'One month', 'Until the baby was born', 0, 19),
(11, 'On which day was the baby circumcised?', 'Eighth day', 'Seventh day', 'Tenth day', 'Twelfth day', 0, 20),
(11, 'Who initially insisted the baby be called John?', 'Elizabeth', 'Zechariah', 'Mary', 'The neighbors', 0, 21),
(11, 'What did Zechariah ask for to write the name?', 'A writing tablet', 'A scroll', 'A piece of parchment', 'A stone', 0, 22),
(11, 'What is the "horn of salvation" raised up in?', 'The house of David', 'The temple', 'Jerusalem', 'The wilderness', 0, 23),
(11, 'What will the child (John) be called in Zechariah''s prophecy?', 'Prophet of the Most High', 'The Messiah', 'The Voice', 'The Baptist', 0, 24),
(11, 'Where did John live until his public appearance?', 'The wilderness', 'The temple', 'Nazareth', 'Jerusalem', 0, 25);
