// 25-question pools per range. Use subsets for easier difficulties.

export type QA = { chapter: number; question: string; options: string[]; answer: number };

export const GEN_1_11: QA[] = [
  { chapter: 1, question: "What is created on Day 1?", options: ["Light", "Sky", "Land", "Animals"], answer: 0 },
  { chapter: 1, question: "Humans are made in whose image?", options: ["Angels", "God", "Kings", "Animals"], answer: 1 },
  { chapter: 2, question: "Garden planted in...", options: ["Hebron", "Eden", "Bethel", "Babel"], answer: 1 },
  { chapter: 2, question: "Eve formed from Adam's...", options: ["Head", "Rib", "Foot", "Heart"], answer: 1 },
  { chapter: 3, question: "Who tempted Eve?", options: ["Lion", "Serpent", "Angel", "Prophet"], answer: 1 },
  { chapter: 3, question: "They sewed ______ leaves.", options: ["Olive", "Fig", "Palm", "Vine"], answer: 1 },
  { chapter: 4, question: "Who killed Abel?", options: ["Lamech", "Cain", "Seth", "Enoch"], answer: 1 },
  { chapter: 4, question: "Jubal is father of...", options: ["Herders", "Musicians", "Smiths", "Kings"], answer: 1 },
  { chapter: 5, question: "Oldest lifespan?", options: ["Lamech", "Jared", "Methuselah", "Noah"], answer: 2 },
  { chapter: 5, question: "Enoch was...", options: ["Killed", "Translated", "Banished", "Drowned"], answer: 1 },
  { chapter: 6, question: "Why flood?", options: ["Overpopulation", "Violence/wickedness", "Famine", "Idols"], answer: 1 },
  { chapter: 6, question: "Ark length in cubits?", options: ["100", "200", "300", "400"], answer: 2 },
  { chapter: 7, question: "Rain lasted...", options: ["20", "30", "40", "50"], answer: 2 },
  { chapter: 7, question: "Clean animals went by...", options: ["Twos", "Sevens", "Threes", "Fours"], answer: 1 },
  { chapter: 8, question: "Bird that returned with leaf", options: ["Raven", "Dove", "Eagle", "Sparrow"], answer: 1 },
  { chapter: 8, question: "First act after ark?", options: ["Built city", "Built altar", "Planted field", "Made law"], answer: 1 },
  { chapter: 9, question: "Covenant sign with Noah", options: ["Circumcision", "Rainbow", "Sabbath", "Oil"], answer: 1 },
  { chapter: 9, question: "Prohibition given", options: ["No meat", "No blood", "No wine", "No salt"], answer: 1 },
  { chapter: 10, question: "Mighty hunter", options: ["Ham", "Cush", "Nimrod", "Japheth"], answer: 2 },
  { chapter: 10, question: "Table of...", options: ["Nations", "Kings", "Laws", "Prophets"], answer: 0 },
  { chapter: 11, question: "City they built", options: ["Ur", "Nineveh", "Babel", "Haran"], answer: 2 },
  { chapter: 11, question: "Purpose of tower", options: ["Worship", "Make a name", "Defense", "Astronomy"], answer: 1 },
  { chapter: 11, question: "Judgment at Babel", options: ["Fire", "Flood", "Confused languages", "Plague"], answer: 2 },
  { chapter: 11, question: "Abram's father", options: ["Nahor", "Terah", "Serug", "Peleg"], answer: 1 },
  { chapter: 11, question: "Abram's wife", options: ["Hagar", "Sarai", "Rebekah", "Leah"], answer: 1 },
  // Extra hard set to enable non-overlapping Advanced (10 more)
  { chapter: 1, question: "Hebrew for 'form' often contrasted with 'bara'?", options: ["Asah", "Yatsar", "Qal", "Kara"], answer: 1 },
  { chapter: 2, question: "River encircling Havilah where gold is found", options: ["Gihon", "Pishon", "Tigris", "Euphrates"], answer: 1 },
  { chapter: 3, question: "First gospel promise points to whose seed?", options: ["Man", "Woman", "Serpent", "Abraham"], answer: 1 },
  { chapter: 4, question: "City Cain built was named after", options: ["Enoch", "Lamech", "Methushael", "Irad"], answer: 0 },
  { chapter: 5, question: "Refrain repeated in genealogy", options: ["And he lived", "And he died", "And he reigned", "And he walked"], answer: 1 },
  { chapter: 6, question: "Word describing Noah in his generation", options: ["Wise", "Mighty", "Blameless", "Royal"], answer: 2 },
  { chapter: 8, question: "Number of days waters prevailed", options: ["100", "120", "150", "200"], answer: 2 },
  { chapter: 9, question: "Canaan was whose son?", options: ["Shem", "Ham", "Japheth", "Arphaxad"], answer: 1 },
  { chapter: 10, question: "Nimrod's kingdom began with", options: ["Babel", "Ur", "Nineveh", "Haran"], answer: 0 },
  { chapter: 11, question: "Language state before Babel", options: ["Many tongues", "One language", "Two languages", "Three dialects"], answer: 1 },
];

export const GEN_12_25: QA[] = [
  { chapter: 12, question: "Abram's age leaving Haran", options: ["70", "75", "80", "99"], answer: 1 },
  { chapter: 12, question: "Who went with Abram?", options: ["Eliezer", "Lot", "Ishmael", "Benjamin"], answer: 1 },
  { chapter: 13, question: "Lot chose the...", options: ["Negev", "Plain of Jordan", "Hebron", "Coast"], answer: 1 },
  { chapter: 14, question: "Priest-king who blessed Abram", options: ["Abimelech", "Melchizedek", "Pharaoh", "Bera"], answer: 1 },
  { chapter: 15, question: "Counted as righteousness", options: ["Law", "Faith", "Circumcision", "Works"], answer: 1 },
  { chapter: 15, question: "Covenant ceremony included", options: ["Smoke/fire pot", "Rainbow", "Ark", "Manna"], answer: 0 },
  { chapter: 16, question: "Hagar's son", options: ["Ishmael", "Isaac", "Esau", "Jacob"], answer: 0 },
  { chapter: 17, question: "Covenant sign to Abraham", options: ["Rainbow", "Circumcision", "Sabbath", "Offering"], answer: 1 },
  { chapter: 18, question: "Who interceded for Sodom?", options: ["Lot", "Abraham", "Isaac", "Moses"], answer: 1 },
  { chapter: 19, question: "Lot's wife became...", options: ["Stone", "Pillar of salt", "Sand", "Ash"], answer: 1 },
  { chapter: 20, question: "King who took Sarah", options: ["Pharaoh", "Abimelech", "Bera", "Hiram"], answer: 1 },
  { chapter: 21, question: "Abraham's age at Isaac's birth", options: ["86", "90", "99", "100"], answer: 3 },
  { chapter: 21, question: "Who laughed?", options: ["Abraham", "Sarah", "Lot", "Isaac"], answer: 1 },
  { chapter: 22, question: "Mount of sacrifice", options: ["Sinai", "Moriah", "Carmel", "Zion"], answer: 1 },
  { chapter: 22, question: "Substitute provided", options: ["Lamb", "Ram", "Goat", "Bull"], answer: 1 },
  { chapter: 23, question: "Sarah died at age", options: ["90", "120", "127", "130"], answer: 2 },
  { chapter: 23, question: "Burial place purchased", options: ["Hebron - Machpelah", "Bethel", "Beersheba", "Jerusalem"], answer: 0 },
  { chapter: 24, question: "Servant found a wife for", options: ["Abraham", "Isaac", "Jacob", "Joseph"], answer: 1 },
  { chapter: 24, question: "Rebekah's brother", options: ["Haran", "Nahor", "Laban", "Bethuel"], answer: 2 },
  { chapter: 25, question: "Esau and Jacob were sons of", options: ["Abraham", "Isaac", "Jacob", "Joseph"], answer: 1 },
  { chapter: 25, question: "Esau sold birthright for", options: ["Gold", "Lentil stew", "Goats", "Bread"], answer: 1 },
  { chapter: 12, question: "Promise to Abram included", options: ["Great nation", "Temple", "King", "Law"], answer: 0 },
  { chapter: 17, question: "Name change to Abraham signified", options: ["Kingdom", "Many nations", "Priesthood", "Prophecy"], answer: 1 },
  { chapter: 18, question: "Visitors to Abraham were", options: ["Three men", "Prophets", "Kings", "Shepherds"], answer: 0 },
  { chapter: 25, question: "Keturah was", options: ["Sarah's maid", "Abraham's later wife", "Hagar's sister", "Lot's wife"], answer: 1 },
  // Extra hard set
  { chapter: 12, question: "Land promised to Abram's offspring was", options: ["Egypt", "Canaan", "Aram", "Edom"], answer: 1 },
  { chapter: 13, question: "Where did Abram dwell after Lot separated?", options: ["Zoar", "Hebron", "Bethel", "Jericho"], answer: 1 },
  { chapter: 14, question: "Valley where kings fought", options: ["Aijalon", "Shaveh", "Siddim", "Elah"], answer: 2 },
  { chapter: 15, question: "Stars metaphor illustrates", options: ["Descendants", "Years", "Cities", "Kings"], answer: 0 },
  { chapter: 17, question: "Age when circumcision commanded", options: ["On eighth day", "At one year", "At birth", "At twelve"], answer: 0 },
  { chapter: 18, question: "Sarah laughed because", options: ["Strangers joked", "She was old", "Abraham laughed", "Angel rebuked"], answer: 1 },
  { chapter: 21, question: "Who was sent away with Hagar?", options: ["Ishmael", "Isaac", "Esau", "Lot"], answer: 0 },
  { chapter: 22, question: "What did Abraham name the place?", options: ["El Roi", "YHWH Jireh", "Bethel", "Peniel"], answer: 1 },
  { chapter: 24, question: "Sign requested at the well involved", options: ["Bread", "Water for camels", "Gold", "Song"], answer: 1 },
  { chapter: 25, question: "Jacob purchased birthright with", options: ["Silver", "Lentil stew", "Goats", "Garments"], answer: 1 },
];

export const GEN_26_36: QA[] = [
  { chapter: 26, question: "Who repeated Abraham's sister ruse?", options: ["Jacob", "Isaac", "Esau", "Lot"], answer: 1 },
  { chapter: 26, question: "Where did Isaac prosper?", options: ["Gerar", "Hebron", "Bethel", "Beersheba"], answer: 0 },
  { chapter: 27, question: "Who helped Jacob obtain blessing?", options: ["Rachel", "Rebekah", "Leah", "Zilpah"], answer: 1 },
  { chapter: 28, question: "Jacob's dream location", options: ["Bethel", "Hebron", "Shechem", "Succoth"], answer: 0 },
  { chapter: 29, question: "Jacob married first", options: ["Rachel", "Leah", "Bilhah", "Zilpah"], answer: 1 },
  { chapter: 30, question: "Jacob's wages became", options: ["Gold", "Spotted/speckled flocks", "Cities", "Land"], answer: 1 },
  { chapter: 31, question: "Why did Laban pursue Jacob?", options: ["Taxes", "Stolen idols", "War", "Sheep"], answer: 1 },
  { chapter: 32, question: "With whom did Jacob wrestle?", options: ["Esau", "An angel", "A priest", "A man"], answer: 1 },
  { chapter: 33, question: "Jacob named the place for booths", options: ["Bethel", "Succoth", "Shechem", "Peniel"], answer: 1 },
  { chapter: 34, question: "Dinah incident city", options: ["Hebron", "Bethel", "Shechem", "Beersheba"], answer: 2 },
  { chapter: 35, question: "Name change to", options: ["Judah", "Israel", "Joseph", "Benjamin"], answer: 1 },
  { chapter: 26, question: "Wells dispute resolved by", options: ["Treaty", "War", "Flight", "Judgment"], answer: 0 },
  { chapter: 27, question: "Esau planned to", options: ["Bless Jacob", "Kill Jacob", "Sell land", "Leave"], answer: 1 },
  { chapter: 28, question: "Stone pillar poured with", options: ["Water", "Oil", "Wine", "Blood"], answer: 1 },
  { chapter: 29, question: "Leah's son's name meaning 'praise'", options: ["Reuben", "Levi", "Judah", "Issachar"], answer: 2 },
  { chapter: 30, question: "Who bore Joseph?", options: ["Leah", "Rachel", "Zilpah", "Bilhah"], answer: 1 },
  { chapter: 31, question: "Who stole household gods?", options: ["Leah", "Rachel", "Rebekah", "Zilpah"], answer: 1 },
  { chapter: 32, question: "Jacob named the place of wrestling", options: ["Bethel", "Peniel", "Succoth", "Mahanaim"], answer: 1 },
  { chapter: 33, question: "Jacob bowed before", options: ["Laban", "Esau", "Pharaoh", "Angel"], answer: 1 },
  { chapter: 35, question: "Rachel died near", options: ["Hebron", "Bethlehem", "Bethel", "Jericho"], answer: 1 },
  { chapter: 36, question: "Chapter records genealogies of", options: ["Jacob", "Esau (Edom)", "Ishmael", "Abraham"], answer: 1 },
  { chapter: 34, question: "Simeon and Levi did what?", options: ["Made peace", "Took vengeance", "Fled", "Traded"], answer: 1 },
  { chapter: 26, question: "Name of the well of oath", options: ["Beer-lahai-roi", "Beersheba", "En-gedi", "Elim"], answer: 1 },
  { chapter: 35, question: "Who was buried in Machpelah in this range?", options: ["Rachel", "Leah", "Isaac", "Esau"], answer: 2 },
  { chapter: 35, question: "Deborah (Rebekah's nurse) buried under", options: ["Oak of weeping", "Palm of Deborah", "Tamarisk", "Cedar"], answer: 0 },
  // Extra hard set
  { chapter: 26, question: "Name given to the well of contention", options: ["Esek", "Sitnah", "Rehoboth", "Shibah"], answer: 0 },
  { chapter: 26, question: "Name given to the second disputed well", options: ["Esek", "Sitnah", "Rehoboth", "En-mishpat"], answer: 1 },
  { chapter: 26, question: "Name given to the spacious well", options: ["Esek", "Sitnah", "Rehoboth", "En-dor"], answer: 2 },
  { chapter: 28, question: "Meaning of Bethel", options: ["House of God", "Gate of heaven", "Place of vision", "God sees"], answer: 0 },
  { chapter: 29, question: "Laban's daughters are", options: ["Rachel & Bilhah", "Leah & Rachel", "Zilpah & Bilhah", "Leah & Tamar"], answer: 1 },
  { chapter: 30, question: "Mandrakes episode involved", options: ["Leah & Rachel", "Jacob & Esau", "Isaac & Rebekah", "Dinah & Shechem"], answer: 0 },
  { chapter: 31, question: "Witness heap named", options: ["Mizpah", "Gilgal", "Eben-ezer", "Gerizim"], answer: 0 },
  { chapter: 32, question: "Jacob's limp was from", options: ["Broken leg", "Hip socket touched", "Ankle twist", "Stone"], answer: 1 },
  { chapter: 35, question: "Benjamin's initial name by Rachel", options: ["Ben-oni", "Ben-hur", "Ben-ammi", "Benaiah"], answer: 0 },
  { chapter: 36, question: "Esau is", options: ["Edom", "Moab", "Ammon", "Aram"], answer: 0 },
];

export const GEN_37_50: QA[] = [
  { chapter: 37, question: "Whose dreams angered brothers?", options: ["Benjamin", "Joseph", "Judah", "Reuben"], answer: 1 },
  { chapter: 37, question: "Who proposed selling Joseph?", options: ["Reuben", "Judah", "Simeon", "Levi"], answer: 1 },
  { chapter: 39, question: "Who accused Joseph falsely?", options: ["Cupbearer", "Potiphar's wife", "Baker", "Pharaoh"], answer: 1 },
  { chapter: 40, question: "Whose dream led to restoration?", options: ["Baker", "Cupbearer", "Both", "Neither"], answer: 1 },
  { chapter: 41, question: "Meaning of the two dreams", options: ["War", "Famine after plenty", "Plague", "Freedom"], answer: 1 },
  { chapter: 41, question: "Years of plenty & famine", options: ["5/5", "7/7", "3/3", "10/10"], answer: 1 },
  { chapter: 42, question: "Who was kept in Egypt first?", options: ["Judah", "Levi", "Simeon", "Reuben"], answer: 2 },
  { chapter: 43, question: "Youngest brother", options: ["Levi", "Naphtali", "Benjamin", "Issachar"], answer: 2 },
  { chapter: 44, question: "Who pleaded for Benjamin?", options: ["Reuben", "Judah", "Levi", "Dan"], answer: 1 },
  { chapter: 45, question: "Joseph revealed himself in", options: ["Canaan", "Goshen", "Egypt", "Hebron"], answer: 2 },
  { chapter: 46, question: "Where did Jacob settle?", options: ["Moab", "Goshen", "Philistia", "Edom"], answer: 1 },
  { chapter: 47, question: "Who managed famine distribution?", options: ["Pharaoh", "Joseph", "Judah", "Simeon"], answer: 1 },
  { chapter: 48, question: "Jacob blessed sons of", options: ["Judah", "Levi", "Joseph", "Benjamin"], answer: 2 },
  { chapter: 49, question: "Scepter promise tribe", options: ["Reuben", "Levi", "Judah", "Joseph"], answer: 2 },
  { chapter: 49, question: "Which son likened to fruitful bough?", options: ["Benjamin", "Joseph", "Zebulun", "Issachar"], answer: 1 },
  { chapter: 37, question: "Item dipped in blood", options: ["Tunic", "Cup", "Staff", "Belt"], answer: 0 },
  { chapter: 39, question: "Joseph's status in Potiphar's house", options: ["Slave", "Overseer", "Guard", "Cook"], answer: 1 },
  { chapter: 41, question: "Who advised storing grain?", options: ["Pharaoh", "Joseph", "Magicians", "Cupbearer"], answer: 1 },
  { chapter: 42, question: "Who recognized the brothers?", options: ["Guards", "Joseph", "Servants", "Pharaoh"], answer: 1 },
  { chapter: 45, question: "Reason given for Joseph's suffering", options: ["Punishment", "God sent me to save life", "Chance", "Brothers' plan"], answer: 1 },
  { chapter: 47, question: "Length of Jacob's years in Egypt", options: ["7", "17", "27", "37"], answer: 1 },
  { chapter: 50, question: "Who carried Jacob for burial?", options: ["Sons", "Egyptians", "Friends", "Servants"], answer: 0 },
  { chapter: 50, question: "Joseph's perspective on evil", options: ["Unforgivable", "God meant it for good", "Ignored", "Punished"], answer: 1 },
  { chapter: 50, question: "Joseph's age at death", options: ["90", "100", "110", "120"], answer: 2 },
  { chapter: 50, question: "Joseph's burial instruction", options: ["Cremation", "Bones carried up", "Bury in Egypt", "Sea"], answer: 1 },
  // Extra hard set
  { chapter: 37, question: "Who suggested throwing Joseph into a pit?", options: ["Judah", "Reuben", "Simeon", "Levi"], answer: 1 },
  { chapter: 38, question: "Tamar bore to Judah", options: ["Perez & Zerah", "Er & Onan", "Shem & Ham", "Gershon & Merari"], answer: 0 },
  { chapter: 39, question: "What did Joseph leave in her hand?", options: ["Ring", "Garment", "Staff", "Cup"], answer: 1 },
  { chapter: 40, question: "Cupbearer's dream featured", options: ["Three baskets", "Three branches", "Seven cows", "Seven heads"], answer: 1 },
  { chapter: 41, question: "Joseph's Egyptian name", options: ["Imhotep", "Zaphenath-paneah", "Potiphera", "Ptah"], answer: 1 },
  { chapter: 42, question: "Money was found in", options: ["Pharaoh's house", "Each man's sack", "Joseph's cup", "A pit"], answer: 1 },
  { chapter: 43, question: "Gift taken to Joseph included", options: ["Gold", "Balm & honey", "Horses", "Oil"], answer: 1 },
  { chapter: 44, question: "Where was the silver cup placed?", options: ["Simeon's sack", "Levi's sack", "Benjamin's sack", "Judah's sack"], answer: 2 },
  { chapter: 47, question: "Years Jacob lived", options: ["130", "137", "147", "155"], answer: 2 },
  { chapter: 48, question: "Younger son blessed above the elder", options: ["Manasseh", "Ephraim", "Benjamin", "Dan"], answer: 1 },
];

export function pickDifficulty(pool: QA[], level: "beginner" | "intermediate" | "advanced"): QA[] {
  // With 35 items per pool now:
  // - Beginner: first 10 (easiest)
  // - Intermediate: next 15 (10–24)
  // - Advanced: last 25 (10 extra hard + 15 mid) => indices 10–34
  if (level === "beginner") return pool.slice(0, 10);
  if (level === "intermediate") return pool.slice(10, 25);
  return pool.slice(10, 35);
}


