-- Create study_groups table
create table if not exists public.study_groups (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    invite_code text unique not null,
    created_by uuid references auth.users(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create study_group_members table
create table if not exists public.study_group_members (
    id bigint generated by default as identity primary key,
    group_id bigint references public.study_groups(id) on delete cascade not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    role text check (role in ('admin', 'member')) default 'member' not null,
    joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(group_id, user_id)
);

-- Enable RLS
alter table public.study_groups enable row level security;
alter table public.study_group_members enable row level security;

-- Policies for study_groups

-- Everyone can view a group if they know the ID (or we filter by membership in the select query usually)
-- But mostly, we only want members to see the group details, or people searching by invite code.
create policy "Groups are viewable by members"
    on public.study_groups for select
    using (
        auth.uid() in (
            select user_id from public.study_group_members where group_id = id
        )
        or created_by = auth.uid()
    );

create policy "Anyone can finding a group by invite code"
    on public.study_groups for select
    using ( true ); -- We rely on the app to only show relevant ones, but 'select' needs to be open to check invite codes.
                    -- A cleaner way is to separate 'public info' vs 'private info', but for now this is simple.

create policy "Users can create groups"
    on public.study_groups for insert
    with check ( auth.uid() = created_by );

create policy "Admins can update groups"
    on public.study_groups for update
    using (
        auth.uid() in (
            select user_id from public.study_group_members
            where group_id = id and role = 'admin'
        )
        or created_by = auth.uid()
    );

-- Policies for study_group_members

create policy "Members can view other members in their group"
    on public.study_group_members for select
    using (
        group_id in (
            select group_id from public.study_group_members where user_id = auth.uid()
        )
    );

create policy "Users can join groups (insert themselves)"
    on public.study_group_members for insert
    with check ( auth.uid() = user_id );

-- Indexes for performance
create index if not exists study_groups_created_by_idx on public.study_groups(created_by);
create index if not exists study_groups_invite_code_idx on public.study_groups(invite_code);
create index if not exists study_group_members_group_id_idx on public.study_group_members(group_id);
create index if not exists study_group_members_user_id_idx on public.study_group_members(user_id);
