// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kejiqzpfiyamjznpdjrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlamlxenBmaXlhbWp6bnBkanJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzcxNjgsImV4cCI6MjA2NjYxMzE2OH0.KVGQxsCFGjHTq-vzpVvk29LnAaSvrW2QKp1r4e8x038";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);